run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy
      - io.WriteString
      - math/rand.Read

  govet:
    enable-all: false

  gofmt:
    simplify: true

  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused

    - path: testutil/
      linters:
        - unused

    - linters:
        - staticcheck
      text: "SA5011"

    - linters:
        - errcheck
      text: "rand.Read"

  max-issues-per-linter: 50
  max-same-issues: 10
