run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - gosec
    - gocyclo
    - revive
    - prealloc
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy
      - io.WriteString
      - math/rand.Read

  govet:
    enable-all: false

  gofmt:
    simplify: true

  gosec:
    excludes:
      - G104
      - G304

  gocyclo:
    min-complexity: 15

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
        - gosec
        - prealloc

    - path: testutil/
      linters:
        - unused
        - gosec

    - linters:
        - staticcheck
      text: "SA5011"

    - linters:
        - errcheck
      text: "rand.Read"

    - linters:
        - revive
      text: "exported"

  max-issues-per-linter: 50
  max-same-issues: 10
